### ISSUE TITLE
Foreign key constraint error on new Mura plugin install

### ISSUE THREAD

**Issue by favog** [ten24/slatwall#5122] opened 2016-12-28 20:23 UTC
There’s something going on with the mura-slatwall-plugin with the newest version of mura.  I have a clean install of Mura 7 running  on an ubuntu 14.04 server running Lucee 5.1.0.34 and  mysql 5.5.53.
 
Downloaded your connector from github and am getting the error below.  

500 Error
Datasource: mura 

SQL: INSERT INTO	SwPaymentTerm ( paymentTermID,activeFlag,termID,paymentTermName,sortOrder ) VALUES ( '27f223d1a5b7cba92e783c926e29efc6' , 1 , '23c6a8c6e1bfc7f2c6cc29d467661eb9' , 'Net 30' , '1' ) 

Code: 0 

Type: database 

Cannot add or update a child row: a foreign key constraint fails (`mura`.`SwPaymentTerm`, CONSTRAINT `FKEFA81A6EECEE6C49` FOREIGN KEY (`termID`) REFERENCES `SwTerm` (`termID`)) 

			
				lucee.runtime.exp.DatabaseException: 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:932)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192)
	at lucee.runtime.type.util.QueryUtil.execute(QueryUtil.java:308)
	at lucee.runtime.type.QueryImpl.execute(QueryImpl.java:272)
	at lucee.runtime.type.QueryImpl.<init>(QueryImpl.java:218)
	at lucee.runtime.tag.Query.executeDatasoure(Query.java:834)
	at lucee.runtime.tag.Query.doEndTag(Query.java:594)
	at org.hibachi.hibachidao_cfc$cf.udfCall2(/Slatwall/org/Hibachi/HibachiDAO.cfc:394)
	at org.hibachi.hibachidao_cfc$cf.udfCall(/Slatwall/org/Hibachi/HibachiDAO.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:210)
	at lucee.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:781)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:814)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1614)
	at org.hibachi.hibachidao_cfc$cf.udfCall2(/Slatwall/org/Hibachi/HibachiDAO.cfc:366)
	at org.hibachi.hibachidao_cfc$cf.udfCall(/Slatwall/org/Hibachi/HibachiDAO.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:224)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:692)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:575)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1898)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:753)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1599)
	at org.hibachi.hibachidataservice_cfc$cf.udfCall(/Slatwall/org/Hibachi/HibachiDataService.cfc:105)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:224)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:772)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:753)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1599)
	at org.hibachi.hibachidataservice_cfc$cf.udfCall(/Slatwall/org/Hibachi/HibachiDataService.cfc:26)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:210)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:693)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:575)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1915)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:814)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1614)
	at application_cfc$cf.udfCall(/Slatwall/Application.cfc:93)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:224)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:772)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:753)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1599)
	at org.hibachi.hibachi_cfc$cf.udfCall1(/Slatwall/org/Hibachi/Hibachi.cfc:643)
	at org.hibachi.hibachi_cfc$cf.udfCall(/Slatwall/org/Hibachi/Hibachi.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:224)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:772)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:753)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1599)
	at org.hibachi.hibachi_cfc$cf.udfCall1(/Slatwall/org/Hibachi/Hibachi.cfc:210)
	at org.hibachi.hibachi_cfc$cf.udfCall(/Slatwall/org/Hibachi/Hibachi.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:224)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:692)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:575)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1898)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:753)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1599)
	at slatwall.integrationservices.mura.model.handler.handler_cfc$cf.udfCall(/savaWRM/Slatwall/integrationServices/mura/model/handler/Handler.cfc:73)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:210)
	at lucee.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:781)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:814)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1614)
	at integrationservices.mura.model.handler.muraeventhandler_cfc$cf.udfCall2(/Slatwall/integrationServices/mura/model/handler/MuraEventHandler.cfc:804)
	at integrationservices.mura.model.handler.muraeventhandler_cfc$cf.udfCall(/Slatwall/integrationServices/mura/model/handler/MuraEventHandler.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:210)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:693)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:575)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1915)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:814)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1614)
	at slatwall_mura405.eventhandler_cfc$cf.udfCall(/plugins/slatwall-mura/eventHandler.cfc:159)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:210)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:693)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:575)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1911)
	at lucee.runtime.tag.Invoke.doComponent(Invoke.java:221)
	at lucee.runtime.tag.Invoke.doEndTag(Invoke.java:194)
	at plugin.pluginmanager_cfc$cf.udfCall3(/mura/plugin/pluginManager.cfc:1608)
	at plugin.pluginmanager_cfc$cf.udfCall(/mura/plugin/pluginManager.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:210)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:693)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:575)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1915)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:814)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1614)
	at config.appcfc.onapplicationstart_include_cfm$cf.call(/config/appcfc/onApplicationStart_include.cfm:480)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:918)
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:833)
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:828)
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:819)
	at admin.application_cfc$cf.udfCall(/admin/Application.cfc:145)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:224)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:772)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:753)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1599)
	at admin.framework_cfc$cf.udfCall6(/admin/framework.cfc:1082)
	at admin.framework_cfc$cf.udfCall(/admin/framework.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:224)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:772)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:753)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1599)
	at admin.framework_cfc$cf.udfCall2(/admin/framework.cfc:439)
	at admin.framework_cfc$cf.udfCall(/admin/framework.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:224)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:692)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:575)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1898)
	at lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:422)
	at lucee.runtime.listener.ModernAppListener.onApplicationStart(ModernAppListener.java:301)
	at lucee.runtime.PageContextImpl.initApplicationContext(PageContextImpl.java:2910)
	at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:121)
	at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:43)
	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2293)
	at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2284)
	at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2252)
	at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:891)
	at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:102)
	at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

			

Column: 0
ID: ??
Line: 394
Raw Trace: org.hibachi.hibachidao_cfc$cf.udfCall2(/Slatwall/org/Hibachi/HibachiDAO.cfc:394)
Template: /var/www/html/Slatwall/org/Hibachi/HibachiDAO.cfc
Type: cfml

Column: 0
ID: ??
Line: 366
Raw Trace: org.hibachi.hibachidao_cfc$cf.udfCall2(/Slatwall/org/Hibachi/HibachiDAO.cfc:366)
Template: /var/www/html/Slatwall/org/Hibachi/HibachiDAO.cfc
Type: cfml

Column: 0
ID: ??
Line: 105
Raw Trace: org.hibachi.hibachidataservice_cfc$cf.udfCall(/Slatwall/org/Hibachi/HibachiDataService.cfc:105)
Template: /var/www/html/Slatwall/org/Hibachi/HibachiDataService.cfc
Type: cfml

Column: 0
ID: ??
Line: 26
Raw Trace: org.hibachi.hibachidataservice_cfc$cf.udfCall(/Slatwall/org/Hibachi/HibachiDataService.cfc:26)
Template: /var/www/html/Slatwall/org/Hibachi/HibachiDataService.cfc
Type: cfml

Column: 0
ID: ??
Line: 93
Raw Trace: application_cfc$cf.udfCall(/Slatwall/Application.cfc:93)
Template: /var/www/html/Slatwall/Application.cfc
Type: cfml

Column: 0
ID: ??
Line: 643
Raw Trace: org.hibachi.hibachi_cfc$cf.udfCall1(/Slatwall/org/Hibachi/Hibachi.cfc:643)
Template: /var/www/html/Slatwall/org/Hibachi/Hibachi.cfc
Type: cfml

Column: 0
ID: ??
Line: 210
Raw Trace: org.hibachi.hibachi_cfc$cf.udfCall1(/Slatwall/org/Hibachi/Hibachi.cfc:210)
Template: /var/www/html/Slatwall/org/Hibachi/Hibachi.cfc
Type: cfml

Column: 0
ID: ??
Line: 73
Raw Trace: slatwall.integrationservices.mura.model.handler.handler_cfc$cf.udfCall(/savaWRM/Slatwall/integrationServices/mura/model/handler/Handler.cfc:73)
Template: /var/www/html/Slatwall/integrationServices/mura/model/handler/Handler.cfc
Type: cfml

Column: 0
ID: ??
Line: 804
Raw Trace: integrationservices.mura.model.handler.muraeventhandler_cfc$cf.udfCall2(/Slatwall/integrationServices/mura/model/handler/MuraEventHandler.cfc:804)
Template: /var/www/html/Slatwall/integrationServices/mura/model/handler/MuraEventHandler.cfc
Type: cfml

Column: 0
ID: ??
Line: 159
Raw Trace: slatwall_mura405.eventhandler_cfc$cf.udfCall(/plugins/slatwall-mura/eventHandler.cfc:159)
Template: /var/www/html/plugins/slatwall-mura/eventHandler.cfc
Type: cfml

Column: 0
ID: ??
Line: 1608
Raw Trace: plugin.pluginmanager_cfc$cf.udfCall3(/mura/plugin/pluginManager.cfc:1608)
Template: /var/www/html/requirements/mura/plugin/pluginManager.cfc
Type: cfml

Column: 0
ID: ??
Line: 480
Raw Trace: config.appcfc.onapplicationstart_include_cfm$cf.call(/config/appcfc/onApplicationStart_include.cfm:480)
Template: /var/www/html/config/appcfc/onApplicationStart_include.cfm
Type: cfml

Column: 0
ID: ??
Line: 145
Raw Trace: admin.application_cfc$cf.udfCall(/admin/Application.cfc:145)
Template: /var/www/html/admin/Application.cfc
Type: cfml

Column: 0
ID: ??
Line: 1082
Raw Trace: admin.framework_cfc$cf.udfCall6(/admin/framework.cfc:1082)
Template: /var/www/html/admin/framework.cfc
Type: cfml

Column: 0
ID: ??
Line: 439
Raw Trace: admin.framework_cfc$cf.udfCall2(/admin/framework.cfc:439)
Template: /var/www/html/admin/framework.cfc
Type: cfml

Attempted Chris Kent's suggestion to no avail.

delete the /custom/config/insertedData.txt.cfm
change line 32 in HibachiDataService.cfc https://github.com/ten24/slatwall/blob/master/org/Hibachi/HibachiDataService.cfc to be
if(retryCount <= 5) {
restart ColdFusion

**Comment by favog** [comment] 2016-12-28 21:25
Also did a git clone of standalone slatwall and got a long series of foreign key constraint issues.

**Comment by damienbkx** [comment] 2016-12-29 16:57
Same problem here when installing slatwall using the Mura plugin
Mura 7.0.6850
Ubuntu 16.0.4 LTS
Lucee 5.1.0.34
MySql 5.7.16

**Comment by damienbkx** [comment] 2017-02-02 16:55
Did some more testing. turns out is it a bug on the Lucee side and more specifically with the ORM libraries used by Lucee.

Lucee uses a very old version of Hibernate (3.5). 
I've tested the installation with ColdFusion and it works like a charm, but Coldfusion (2016 release) is using a more recent version of Hibernate ORM (4.3.10)
Apparently Hibernate 4 is in beta on the lucee side, so I guess we just have to wait or use CF 2016

**Comment by sumitverma** [comment] 2018-08-23 14:33
Closing as it was Lucee issues. Lucee 4.5 and 5.2+ is supported and confirmed to be working.

**Closed by sumitverma** 2018-08-23 14:33 UTC
